### ISSUE TITLE
Research NHDPlus HR Stream Order Attributes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyGNAT#2]
ArcGNAT used to calculate stream order.  But the latest version of NHD, the so called "[NHDPlus High Resolution](https://www.usgs.gov/core-science-systems/ngp/national-hydrography/nhdplus-high-resolution)" already contains many attributes, including stream order.

The goal of this ticket is to research the NHDPlus HR attributes related to stream order and document the findings on this issue. Specific questions are:

* Which stream order methods are captured?
* Does it include the strahler stream order attribute?
* Is the stream order provided in NHDPlus HR suitable for use in GNAT? Does it make the old arcGNAT stream order tool redundant?

The 80 page PDF [manual describing NHDPlus HR](https://pubs.er.usgs.gov/publication/ofr20191096) is a good place to start.

**Comment by joewheaton** [comment]
Also, bare in mind that stream order is a function of network extent used.
For example, perennial stream order is very different than entire network.

**Comment by KellyMWhitehead** [comment]
(Closing, reopen if further discussion is needed.)

From the [nhd plus user guide](https://pubs.usgs.gov/of/2019/1096/ofr20191096.pdf) 



![Image](https://user-images.githubusercontent.com/10746997/198338486-0e73b25b-2db4-45c5-9b7b-2e67f2572174.png)



StreamOrder and StreamCalculator: StreamOrder
(fig. 28) in NHDPlus and NHDPlus HR is a modified
version of stream order as defined by Strahler
(1957). The Strahler stream-order algorithm does
not account for flow splits in the network, whereas
the algorithm used in NHDPlus and NHDPlus HR
for stream order takes flow splits into consideration.
The StreamCalculator value-added attribute is
a modification of the StreamOrder value-added
attribute. StreamCalculator is a variable created to
assist with tracking divergences and is computed
with StreamOrder. These value-added attributes are
computed from upstream to downstream. The method
used for assigning StreamOrder and StreamCalculator
is as follows:
• All headwater or “start” reaches are assigned a
Strahler order of “1.”
• StreamCalculator is assigned the same value as
StreamOrder for all headwater flowlines.
• If there are no divergences, then StreamOrder and
StreamCalculator have the same value; both values
are increased in the manner defined for calculating
the Strahler order.
• When a divergence is reached, the defined main path
(DIVERGENCE = 1) is assigned the same values for
StreamOrder and StreamCalculator on the basis of
the inflows to the divergence.
• The defined minor-path divergence
(DIVERGENCE = 2) is assigned the StreamOrder
value based on the inflows to the divergence, but
StreamCalculator is assigned the value “0.” As
the minor-path divergence continues downstream,
the StreamCalculator value remains “0,” and
the StreamOrder value cannot increase until the
flowline is combined with another flowline that
has a StreamCalculator value greater than 0. This
sequence allows multiple minor-path divergences to
intertwine without increasing the StreamOrder of the
minor path.
• When two minor-path flowlines with
StreamCalculator values equal to 0 and different
StreamOrder values join, the larger StreamOrder
value is maintained, and StreamCalculator remains
equal to 0.
• Because StreamOrder cannot increase if
StreamCalculator is equal to 0, when a minor path
rejoins the main path, the main path StreamOrder
value is maintained.
